### ISSUE TITLE
Some unit tests failed on MacOS

### ISSUE THREAD

**Issue by Jinnkunn** [matt24smith/mproxy-dispatcher#1]
The following tests failed when running `cargo test server`:
test_server_ipv6_multicast
test_server_ipv6_unicast

The following test failed when running `cargo test client`:
test_client_socket_stream_multicast_ipv6

**Comment by Jinnkunn** [comment]
The Failed Tests Identified Two Key Issues with MacOS:
1. Internet interface selection
2. Unspecified IP Address usage

**Comment by Jinnkunn** [comment]
I've written a [blog post](https://blog.jinkunchen.com/posts/potential-errors-with-unspecified-address/) discussing the potential errors associated with unspecified IP addresses on MacOS (`[::]` and `0.0.0.0`).

**Comment by matt24smith** [comment]
Thanks for testing this out! Can you try out the fixes in the development branch "testing_no_socket2" and see if this fixes it for you? This fixed the failed tests for me when using MacOS 13.3.1. 

I'd still like to be able to use the unspecified address when setting the listening socket to indicate that incoming data may be received from any address. When using the unspecified address as the target socket address, it fails with "No route to host" as described in your blog post. It does appear that other OS will redirect to the loopback address, so I've attempted to find a solution that doesn't rely on this behaviour.

One part I still don't understand is which socket interface to use for MacOS when setting the client outbound target IP. In my testing I found that interface with index 12 works but I don't know why (https://github.com/matt24smith/mproxy-dispatcher/blob/ef22097d8977e67d40aa691d5329c879d694ad1b/client/src/lib.rs#L114)

**Comment by matt24smith** [comment]
@Jinnkunn Thanks for your suggestion to use the default_net crate, I've added this when building for macos to determine the correct network interface
